import { Star, Quote } from "lucide-react";

const testimonialsData = [
  { rating: 5 },
  { rating: 5 },
  { rating: 5 },
];

const TestimonialsSection = () => {
  return (
    <section className="py-20 bg-gradient-to-b from-purple-50 to-blue-50">
      <div className="max-w-6xl mx-auto px-6">
        <div className="text-center mb-16 fade-in-up">
          <h2 className="text-4xl md:text-5xl font-bold text-gray-900 mb-6" data-i18n="testimonialsTitle">
            What Our Students Say
          </h2>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto" data-i18n="testimonialsSubtitle">
            Join thousands of professionals who have transformed their careers with our AI prompt engineering course
          </p>
        </div>

        <div className="grid md:grid-cols-3 gap-8">
          {testimonialsData.map((testimonial, index) => {
            const num = index + 1;
            return (
              <div
                key={index}
                className="bg-white rounded-2xl p-8 shadow-lg border border-gray-100 hover:shadow-2xl transition-all duration-300 hover:scale-[1.02] fade-in-up"
                style={{ animationDelay: `${index * 0.1}s` }}
              >
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-1">
                    {[...Array(testimonial.rating)].map((_, i) => (
                      <Star key={i} className="h-5 w-5 fill-yellow-400 text-yellow-400" />
                    ))}
                  </div>
                  <Quote className="h-8 w-8 text-purple-200" />
                </div>

                <p className="text-gray-700 mb-6 leading-relaxed" data-i18n={`testimonial${num}Content`}>
                  {/* This text will be replaced by i18n.js */}
                </p>

                <div className="flex items-center gap-3">
                  <div className="w-12 h-12 bg-gradient-ai rounded-full flex items-center justify-center text-white font-semibold" data-i18n-initials-from={`testimonial${num}Name`}>
                    {/* Avatar initials will be generated by i18n.js */}
                  </div>
                  <div>
                    <div className="font-semibold text-gray-900" data-i18n={`testimonial${num}Name`}>
                      {/* This text will be replaced by i18n.js */}
                    </div>
                    <div className="text-sm text-gray-600" data-i18n={`testimonial${num}Role`}>
                      {/* This text will be replaced by i18n.js */}
                    </div>
                  </div>
                </div>
              </div>
            )
          })}
        </div>
      </div>
    </section>
  );
};

export default TestimonialsSection;
